import type { Candidate } from './types'

export const mockCandidates: Candidate[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    title: 'Senior Software Engineer',
    company: 'Meta',
    location: 'San Francisco, CA',
    avatar: 'SC',
    skills: ['React', 'TypeScript', 'Node.js', 'GraphQL', 'AWS', 'System Design', 'Python', 'PostgreSQL'],
    experience: 6,
    education: 'MS Computer Science, Stanford University',
    summary: 'Full-stack engineer with expertise in building scalable web applications. Led a team of 5 engineers to deliver a real-time collaboration platform serving 2M users.',
    availability: 'two-weeks',
    salaryExpectation: '$180,000 - $220,000'
  },
  {
    id: '2',
    name: 'Marcus Johnson',
    title: 'Staff Engineer',
    company: 'Stripe',
    location: 'New York, NY',
    avatar: 'MJ',
    skills: ['Go', 'Kubernetes', 'AWS', 'Terraform', 'PostgreSQL', 'Redis', 'Microservices', 'System Design'],
    experience: 8,
    education: 'BS Computer Science, MIT',
    summary: 'Infrastructure specialist with deep expertise in payment systems. Designed and built Stripe\'s internal service mesh handling 1B+ requests/day.',
    availability: 'passive',
    salaryExpectation: '$250,000 - $300,000'
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    title: 'Frontend Lead',
    company: 'Airbnb',
    location: 'Seattle, WA',
    avatar: 'ER',
    skills: ['React', 'TypeScript', 'Next.js', 'CSS', 'Design Systems', 'Accessibility', 'Performance Optimization'],
    experience: 5,
    education: 'BS Information Systems, University of Washington',
    summary: 'Frontend specialist passionate about design systems and accessibility. Built Airbnb\'s new design system adopted by 200+ engineers.',
    availability: 'one-month',
    salaryExpectation: '$160,000 - $190,000'
  },
  {
    id: '4',
    name: 'David Kim',
    title: 'ML Engineer',
    company: 'OpenAI',
    location: 'San Francisco, CA',
    avatar: 'DK',
    skills: ['Python', 'PyTorch', 'TensorFlow', 'LLMs', 'MLOps', 'Kubernetes', 'Data Engineering'],
    experience: 4,
    education: 'PhD Machine Learning, UC Berkeley',
    summary: 'Machine learning engineer focused on large language models and production ML systems. Co-authored 3 papers on transformer optimization.',
    availability: 'immediate',
    salaryExpectation: '$200,000 - $250,000'
  },
  {
    id: '5',
    name: 'Jessica Williams',
    title: 'Engineering Manager',
    company: 'Google',
    location: 'Austin, TX',
    avatar: 'JW',
    skills: ['Leadership', 'System Design', 'Java', 'Go', 'Cloud Architecture', 'Agile', 'Mentoring'],
    experience: 10,
    education: 'MBA, Harvard Business School; BS CS, Georgia Tech',
    summary: 'Engineering leader with 10 years of experience building and scaling teams. Grew Google Cloud\'s IAM team from 5 to 35 engineers.',
    availability: 'two-weeks',
    salaryExpectation: '$280,000 - $350,000'
  },
  {
    id: '6',
    name: 'Alex Thompson',
    title: 'DevOps Engineer',
    company: 'Netflix',
    location: 'Los Angeles, CA',
    avatar: 'AT',
    skills: ['AWS', 'Terraform', 'Docker', 'Kubernetes', 'CI/CD', 'Python', 'Monitoring', 'Security'],
    experience: 5,
    education: 'BS Computer Engineering, UCLA',
    summary: 'DevOps specialist with expertise in cloud infrastructure and automation. Built Netflix\'s deployment pipeline serving 200+ microservices.',
    availability: 'one-month',
    salaryExpectation: '$170,000 - $200,000'
  },
  {
    id: '7',
    name: 'Priya Patel',
    title: 'Backend Engineer',
    company: 'Uber',
    location: 'Chicago, IL',
    avatar: 'PP',
    skills: ['Go', 'Java', 'Kafka', 'Redis', 'PostgreSQL', 'Microservices', 'System Design', 'AWS'],
    experience: 4,
    education: 'MS Computer Science, Carnegie Mellon University',
    summary: 'Backend engineer specializing in real-time systems and distributed computing. Optimized Uber\'s ride matching algorithm reducing latency by 40%.',
    availability: 'immediate',
    salaryExpectation: '$150,000 - $180,000'
  },
  {
    id: '8',
    name: 'Michael Brown',
    title: 'Full Stack Developer',
    company: 'Shopify',
    location: 'Remote (US)',
    avatar: 'MB',
    skills: ['Ruby on Rails', 'React', 'TypeScript', 'PostgreSQL', 'Redis', 'GraphQL', 'E-commerce'],
    experience: 3,
    education: 'BS Computer Science, University of Michigan',
    summary: 'Full stack developer with e-commerce expertise. Built Shopify\'s new checkout flow increasing conversion rates by 15%.',
    availability: 'two-weeks',
    salaryExpectation: '$130,000 - $160,000'
  },
  {
    id: '9',
    name: 'Lisa Wang',
    title: 'Data Engineer',
    company: 'Databricks',
    location: 'Denver, CO',
    avatar: 'LW',
    skills: ['Python', 'Spark', 'SQL', 'Airflow', 'AWS', 'dbt', 'Data Modeling', 'Kafka'],
    experience: 5,
    education: 'MS Data Science, Columbia University',
    summary: 'Data engineer passionate about building robust data pipelines. Designed Databricks\' customer analytics platform processing 10TB+ daily.',
    availability: 'passive',
    salaryExpectation: '$165,000 - $195,000'
  },
  {
    id: '10',
    name: 'James Wilson',
    title: 'Security Engineer',
    company: 'Cloudflare',
    location: 'Boston, MA',
    avatar: 'JWi',
    skills: ['Security', 'Go', 'Python', 'Network Security', 'Penetration Testing', 'Cloud Security', 'Compliance'],
    experience: 7,
    education: 'MS Cybersecurity, NYU',
    summary: 'Security engineer with expertise in cloud security and incident response. Led Cloudflare\'s bug bounty program identifying 50+ critical vulnerabilities.',
    availability: 'one-month',
    salaryExpectation: '$190,000 - $230,000'
  }
]
